server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/users/**

        - id: auth-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/auth/**

        - id: address-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/address/**

        - id: product-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/products/**

        - id: orders-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/orders/**

secret:
  token:
    key: J2CUwMG7rSBGNRjFuJuHGJMxxyphMczqALaOIWe76y9
